### Lists

In [42]:
a = [1, 2, 3]
b = ["q", "w", "e"]
c = [1 ,"z", 2.3]
d = [a, b , c]

In [3]:
# Grab from list by index
a[2]  # 3rd element of list a

3

In [4]:
# Grab from list by index
a[-1] # last element of list a

3

In [7]:
# Grab from a list within a list
d[1][1] # second list,  second element

'w'

In [10]:
# Grab from a list within a list
d[0][1:]   # first list, last two elements

[2, 3]

In [38]:
# Change stuff within a list
print(a)
a[1] = "Zach"
print(a)

[1, 2, 3]
[1, 'Zach', 3]


In [43]:
# Add Stuff to a list
a.append("Tom")
print(a)

[1, 2, 3, 'Tom']


### Tuples

In [19]:
a = (1, 2, 3)
b = ("q", "w", "e")
c = (1 ,"z", 2.3)
d = (a, b , c)

In [20]:
# Grab from tuple by index
a[2]  # 3rd element of tuple a

3

In [21]:
# Grab from tuple by index
a[-1] # last element of tuple a

3

In [22]:
# Grab from a tuple within a tuple
d[1][1] # second tuple,  second element

'w'

In [23]:
# Grab from a tuple within a tuple
d[0][1:]   # first tuple, last two elements

(2, 3)

In [24]:
# Change stuff within a list
print(a)
a[1] = "Zach"
print(a)

(1, 2, 3)


TypeError: 'tuple' object does not support item assignment

### TUPLES ARE IMMUTABLE!!!!   YOU CAN"T CHANGE THEM!!!! DON"T TRY!!!!

### Dictionaries

In [56]:
name_age ={}
name_age['Zach'] = 45
name_age['Tom'] = 24
name_age['Abby'] = 71

print(name_age)

{'Zach': 45, 'Tom': 24, 'Abby': 71}


In [57]:
name_age['Zach']

45

In [58]:
more_names_ages = {}
name_age['Frank'] = 5
name_age['Penny'] = 1
name_age['Maggie'] = 11
name_age.update(more_names_ages)

In [59]:
print(name_age)

{'Zach': 45, 'Tom': 24, 'Abby': 71, 'Frank': 5, 'Penny': 1, 'Maggie': 11}


### Data Types

In [25]:
a = 1
type(a)

int

In [26]:
a = 'fox'
type(a)

str

In [27]:
a = 4.5
type(a)

float

In [28]:
a = True
type(a)

bool

### For Loops

In [44]:
vals = [1, 2, 3, 4, 5]
squares = []

for x in vals:
    squares.append(x**2)
    
print(squares)

[1, 4, 9, 16, 25]


In [54]:
# find common numbers in two lists
l1 = [4, 8, 6, 7, 3, 9, 3, 1, 2, 5]
l2 = [4, 2, 6, 5, 7, 9, 3, 1, 3, 3]

common = []
for i in l1:
    if i in l2:
        common.append(i)

print(common)

[4, 6, 7, 3, 9, 3, 1, 2, 5]


### List Comprehensions

In [35]:
# Any easy way to replace a for loop
vals = [1, 2, 3, 4, 5]
squares = [x**2 for x in vals]
print(squares)

squares2 = [[x, x**2] for x in vals]
print(squares2)

[1, 4, 9, 16, 25]
[[1, 1], [2, 4], [3, 9], [4, 16], [5, 25]]


In [52]:
# find common numbers in two lists
l1 = [4, 8, 6, 7, 3, 9, 3, 1, 2, 5]
l2 = [4, 2, 6, 5, 7, 9, 3, 1, 3, 3]

common_num = [i for i in l1 if i in l2]
print(common_num)

[4, 6, 7, 3, 9, 3, 1, 2, 5]


### While Loops

In [46]:
# print the square of the number until the counter hits a limit
c = 0
limit=5
while c < limit:
    print(c**2)
    #whoops we forgot to add to our counter so the loop will continue forever

0
1
4
9
16


In [ ]:
## I don't personally use while loops very often

### Functions

In [ ]:
def square(x):
    return x**2

### Numpy Stuff

In [5]:
import numpy as np
# Create an array from a list  - 1D
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
b = np.array(a)
print(b)
print(b.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [15]:
# Create an array from a list  - 2D
a = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]
b = np.array(a)
print(b)
print(b.shape)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
(2, 10)


In [7]:
#Slicing
# take the first row of b
print(b[0,:])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# take the first two items of the first two coloumns of b
print(b[:2, :2])

[[ 1  2]
 [11 12]]


In [11]:
# take the the last 2 items from the first row of b
print(b[0, -2:])

[ 9 10]


#### Using numpy arrays to mask data

In [28]:
# First lets create a 5x5 array of random integers between 0 - 100:
a = np.random.randint(100, size=(5,5))
print(a)

# Then lets create a mask of the same size with 0/1's as the values
mask = np.random.randint(2, size=(5, 5))
print(mask)

[[56 75 31  7 95]
 [58 99 11 63 30]
 [60 97 44 84  8]
 [79 14 74 66  3]
 [25 93 74 70 10]]
[[0 1 0 1 1]
 [1 0 0 1 1]
 [0 0 1 1 0]
 [0 1 0 1 1]
 [1 0 1 1 1]]


In [29]:
# Lets say we want to only work with data that comes through our mask:
a[mask==1]


# This method takes all the elements  of "a", and returns only those where
# the mask has a value of 1

array([75,  7, 95, 58, 63, 30, 44, 84, 14, 66,  3, 25, 74, 70, 10])

In [31]:
# What if we wanted to do something to the elementes that come through the mask
# but we want to replace the values in the original array

# First lets multiply the non-masked values by 50 and store in a new variable
b = a[mask==1]* 50
print(b)

[3750  350 4750 2900 3150 1500 2200 4200  700 3300  150 1250 3700 3500
  500]


In [33]:
# Then lets replace the elements of the original array with the new values
print(a, '\n')
a[mask==1] = b
print(a)

[[56 75 31  7 95]
 [58 99 11 63 30]
 [60 97 44 84  8]
 [79 14 74 66  3]
 [25 93 74 70 10]] 

[[  56 3750   31  350 4750]
 [2900   99   11 3150 1500]
 [  60   97 2200 4200    8]
 [  79  700   74 3300  150]
 [1250   93 3700 3500  500]]
